name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Clojure Deps
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1105.sh
          chmod +x linux-install-1.11.1.1105.sh
          sudo ./linux-install-1.11.1.1105.sh
      - name: Run tests
        run: clojure -A:deps:test -T:build test
      - name: build jar
        run: clojure -A:deps -T:build ci
